name: deploy-portfolio-api.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - apps/portfolio-backend-hono/**
      - .github/workflows/deploy-portfolio-api.yml
      - packages/about-me/**
      - ./package.json

jobs:
  deploy-worker:
    name: 'Release worker on Cloudflare Workers'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Update App Configurations
        run: pnpm run deploy:prepare-env-backend-hono

      - name: Update About Me Json
        run: pnpm run generate:about-me

      - name: Update Wrangler Config
        run: | 
          env "WRANGLER-CFG-vars.ALLOWED_HOST"="${{ secrets.BACKEND_ENV_ALLOWED_HOST }}" \
          "WRANGLER-CFG-vars.R2_ACCOUNT_ID"="${{ secrets.BACKEND_ENV_R2_ACCOUNT_ID }}" \
          "WRANGLER-CFG-vars.R2_ACCESS_KEY"="${{ secrets.BACKEND_ENV_R2_ACCESS_KEY }}" \
          "WRANGLER-CFG-vars.R2_SECRET_KEY"="${{ secrets.BACKEND_ENV_R2_SECRET_KEY }}" \
          "WRANGLER-CFG-vars.R2_CV_PATH"="${{ secrets.BACKEND_ENV_R2_CV_PATH }}" \
          "WRANGLER-CFG-vars.R2_BUCKET"="${{ secrets.BACKEND_ENV_R2_BUCKET }}" \
          "WRANGLER-CFG-vars.R2_PUBLIC_URL"="${{ secrets.BACKEND_ENV_R2_PUBLIC_URL }}" \
          "WRANGLER-CFG-vars.TURNSTILE_SECRET_KEY"="${{ secrets.BACKEND_ENV_TURNSTILE_SECRET_KEY }}" \
          "WRANGLER-CFG-send_email[0].destination_address"="${{ secrets.BACKEND_ENV_EMAIL_BINDING_1_DESTINATION_ADDRESS }}" \
          "WRANGLER-CFG-send_email[0].name"="EMAIL_BINDING" \
          "WRANGLER-CFG-vars.DESTINATION_ADDRESS"="${{ secrets.BACKEND_ENV_EMAIL_BINDING_1_DESTINATION_ADDRESS }}" \
          node apps/portfolio-backend-hono/scripts/update-wrangler-config.mjs

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: './apps/portfolio-backend-hono/'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
